#!/usr/bin/env python3
"""
Test the Smart Image Generator with Gemini Analysis
"""

from smart_image_generator import SmartImageGenerator
from gemini_handler import GeminiHandler
import json

def test_smart_image_generation():
    print("🧠 Testing Smart Philosophy Image Generation")
    print("=" * 50)
    
    # Create test story data
    gemini = GeminiHandler()
    
    # Generate a story first
    print("📖 Generating Plato's Cave story...")
    story_data = gemini.generate_philosophy_story("Plato's Cave Allegory")
    
    if not story_data:
        print("❌ Story generation failed")
        return
    
    print(f"✅ Story generated: {len(story_data.get('script', ''))} characters")
    print(f"🎬 Hook: {story_data.get('hook', 'N/A')}")
    
    # Extract scenes
    scenes = story_data.get('scenes', [])
    print(f"🎭 Scenes: {len(scenes)}")
    
    # Test smart image generation
    print("\n🎨 Testing Smart Image Generation...")
    smart_gen = SmartImageGenerator()
    
    # Get intelligent analysis and prompts
    print("🧠 Getting Gemini's intelligent analysis...")
    prompt_analysis = smart_gen.analyze_story_and_generate_image_prompts(story_data, scenes)
    
    print(f"\n📋 GEMINI'S ANALYSIS:")
    print(f"Story Analysis: {prompt_analysis.get('story_analysis', 'N/A')}")
    print(f"Overall Aesthetic: {prompt_analysis.get('overall_aesthetic', 'N/A')}")
    
    # Show the intelligent prompts
    scene_prompts = prompt_analysis.get('scene_prompts', [])
    for i, prompt_info in enumerate(scene_prompts):
        print(f"\n🎬 Scene {i+1}: {prompt_info.get('philosophical_concept', 'N/A')}")
        print(f"🎭 Mood: {prompt_info.get('mood', 'N/A')}")
        print(f"🎨 Color Palette: {prompt_info.get('color_palette', 'N/A')}")
        print(f"🖼️  IMAGE PROMPT:")
        print(f"   {prompt_info.get('image_prompt', 'N/A')}")
        print(f"💭 Visual Metaphor: {prompt_info.get('visual_metaphor', 'N/A')}")
    
    # Generate actual images with these intelligent prompts
    print(f"\n🖼️  Generating images with intelligent prompts...")
    image_paths = smart_gen.generate_all_images(story_data, scenes)
    
    print(f"\n✅ RESULTS:")
    print(f"📁 Generated {len(image_paths)} images:")
    for path in image_paths:
        print(f"   - {path}")
    
    print(f"\n🎯 The prompts sent to image generation are now:")
    print(f"   ✅ Contextually aware of the full story")
    print(f"   ✅ Tailored to each scene's philosophical concept") 
    print(f"   ✅ Optimized for classical/cinematic aesthetic")
    print(f"   ✅ Generated by Gemini's deep understanding")
    
    return {
        "story": story_data,
        "analysis": prompt_analysis,
        "images": image_paths
    }

if __name__ == "__main__":
    result = test_smart_image_generation()
    
    if result:
        print(f"\n🎉 Smart image generation test complete!")
        print(f"🔧 Next: Replace the placeholder generation with actual Nano API calls")
        print(f"💡 The prompts are now much more sophisticated and context-aware")